#!/usr/bin/env Rscript
# Builds R/sysdata.rda (the internal `datasheet_questions` list) AND
# renders inst/templates/datasheet_template.{md,qmd} from that same list,
# so use_datasheet()'s static template and build_datasheet_wizard()'s
# interactive prompts never drift out of sync with each other.
#
# The seven sections and their sub-questions follow Gebru et al. 2021,
# "Datasheets for Datasets" (Communications of the ACM), with three
# questions explicitly cross-referencing duboisR's own diagnostic
# functions (audit_composition(), check_proxies(), check_tendentious())
# per the source feedback document's integration proposal.

datasheet_questions <- list(
  motivation = list(
    title = "Motivation",
    questions = c(
      purpose = "For what purpose was the dataset created?",
      funder = "Who funded the creation of the dataset?"
    )
  ),
  composition = list(
    title = "Composition",
    questions = c(
      instances = "What do the instances that comprise the dataset represent?",
      subpopulations = "Are there subpopulation identifiers (e.g. race, gender)? If so, describe them (see duboisR::audit_composition()).",
      sensitive_data = "Does the dataset contain data that might be considered sensitive?",
      missing_info = "Is any information missing from individual instances, and if so, why (see duboisR::audit_composition())?"
    )
  ),
  collection_process = list(
    title = "Collection Process",
    questions = c(
      acquisition = "How was the data associated with each instance acquired?",
      collectors_timeframe = "Who was involved in the data collection process, and over what timeframe?",
      ethical_review = "Were any ethical review processes conducted?"
    )
  ),
  preprocessing = list(
    title = "Preprocessing/cleaning/labeling",
    questions = c(
      was_preprocessed = "Was any preprocessing/cleaning/labeling of the data done?",
      raw_data_saved = "Was the 'raw' data saved in addition to the preprocessed/cleaned/labeled data?",
      software_available = "Is the software used to preprocess/clean/label the data available?",
      identity_proxies = "Are there covariates that act as proxies for protected attributes (see duboisR::check_proxies())?"
    )
  ),
  uses = list(
    title = "Uses",
    questions = c(
      prior_uses = "Has the dataset been used for any tasks already?",
      composition_impact = "Is there anything about the composition of the dataset, or the way it was collected, that might impact future uses?",
      inappropriate_uses = "Are there tasks for which the dataset should not be used (see duboisR::check_tendentious())?"
    )
  ),
  distribution = list(
    title = "Distribution",
    questions = c(
      third_parties = "Will the dataset be distributed to third parties outside of the entity on behalf of which it was created?",
      distribution_mechanism = "How will the dataset be distributed?",
      licensing = "Is the dataset subject to any copyright, licensing, or export-control restrictions?"
    )
  ),
  maintenance = list(
    title = "Maintenance",
    questions = c(
      maintainer = "Who will be supporting/hosting/maintaining the dataset?",
      contact = "How can the owner/curator/manager of the dataset be contacted?",
      updates = "Will the dataset be updated? If so, how often, and by whom?",
      erratum = "Is there an erratum process for reporting errors in the dataset?"
    )
  )
)

usethis::use_data(datasheet_questions, internal = TRUE, overwrite = TRUE)

render_datasheet_body <- function(questions) {
  sections <- vapply(questions, function(sec) {
    qs <- vapply(sec$questions, function(q) paste0("**", q, "**\n\n_Your answer here._\n"), character(1))
    paste0("## ", sec$title, "\n\n", paste(qs, collapse = "\n"))
  }, character(1))
  paste(sections, collapse = "\n\n")
}

body_md <- render_datasheet_body(datasheet_questions)

md_content <- paste0(
  "# Datasheet\n\n",
  "Generated by `duboisR::use_datasheet()`. This scaffolds the structure ",
  "only -- per Gebru et al. 2021, the reflection itself is deliberately ",
  "not automated. Fill in each section yourself; use `duboisR::audit_composition()`, ",
  "`duboisR::check_proxies()`, and `duboisR::check_tendentious()` to get the ",
  "precise statistics referenced below.\n\n",
  body_md, "\n"
)
writeLines(md_content, file.path("inst", "templates", "datasheet_template.md"))

qmd_content <- paste0(
  "---\ntitle: \"Datasheet\"\nformat: html\n---\n\n",
  "Generated by `duboisR::use_datasheet()`. This scaffolds the structure ",
  "only -- per Gebru et al. 2021, the reflection itself is deliberately ",
  "not automated. Fill in each section yourself; use `duboisR::audit_composition()`, ",
  "`duboisR::check_proxies()`, and `duboisR::check_tendentious()` to get the ",
  "precise statistics referenced below.\n\n",
  body_md, "\n"
)
writeLines(qmd_content, file.path("inst", "templates", "datasheet_template.qmd"))

cat("Wrote R/sysdata.rda and inst/templates/datasheet_template.{md,qmd}\n")
