# Shiny module: "Threshold Test" tab -- everything about the search
# decision, in a fixed order: how often people get searched (frequency),
# then how justified those searches are (quality/evidentiary bar). Three
# charts total, each followed by a plain caption (what the chart
# generically shows) and a plain interpretation (what THIS data actually
# shows) -- same pattern as r_dashboard/R/mod_veil_of_darkness.R. The
# interpretation text is generated by duboisR::interpret_search_rate_disparity()
# / interpret_threshold_fit() / interpret_outcome_threshold_comparison(),
# not written inline here, so the CLI/console can reuse the same narration
# later.
#
# The first chart (search rate) used to live on the Veil of Darkness tab,
# paired with the county-level VoD ratio for a "where does the disparity
# concentrate" comparison. It moved here because it was never actually a
# Veil of Darkness test -- not restricted to daylight/dark or the
# intertwilight window -- and belongs with the rest of the search-decision
# diagnostics instead.
#
# The statistical core (summarize_county_search_rates(),
# summarize_county_search_disparity(), aggregate_sufficient_statistics(),
# fit_threshold_test(), compute_outcome_test(),
# compare_outcome_threshold_test()) lives entirely in
# duboisR/R/threshold_test.R (search rate) and veil_of_darkness_charts.R
# (the aggregation helper); this module is a thin reactive wrapper, same
# pattern as the Veil of Darkness tab. This always models
# search_conducted/contraband_found regardless of any outcome selector --
# that pairing is the Threshold Test's own methodology, not a swappable
# outcome, and this tab has no sidebar of its own.
#
# One cached input: results/threshold_test.rds, a list(suff_stats = ...,
# fit = ..., county_search_rates = ..., county_search_disparity = ...) --
# built by duboisR/inst/scripts/precompute_audit.R. suff_stats/fit are
# restricted to the 100 largest counties with >= 1000 stops (fixes
# fit_threshold_test() convergence for the sparser races; doesn't change
# the substantive finding -- see that script's comment) --
# county_search_rates/county_search_disparity are NOT restricted (a plain
# descriptive ratio doesn't need that stabilization). suff_stats is cached
# alongside the fit (both are tiny) so compare_outcome_threshold_test() can
# be derived live in the reactive below instead of needing a fourth cached
# artifact.

threshold_module_ui <- function(id) {
  ns <- NS(id)
  tagList(
    h4("How often drivers get searched, by county"),
    plotOutput(ns("search_rate_plot"), height = "340px"),
    p(
      "Each dot is a county: how often that race's drivers got searched, ",
      "compared to a reference race (near 1.0 = equal rates). This is how ",
      em("often"), " someone gets searched at all -- not whether the search ",
      "turns anything up (see the two charts below for that)."
    ),
    uiOutput(ns("search_rate_interpretation")),

    h4("Threshold Test: search rate vs. hit rate, by county"),
    plotOutput(ns("threshold_plot"), height = "340px"),
    p(
      "Each dot is a county: how often that race's drivers got searched, ",
      "and how often those searches actually found something. The curves are the ",
      "model's best guess at each race's likelihood of carrying contraband. ",
      "A gap that survives this adjustment is hard to explain away as an ",
      "innocent difference in what people are carrying."
    ),
    uiOutput(ns("threshold_interpretation")),

    h4("Naive outcome test vs. infra-marginality-corrected Threshold Test"),
    plotOutput(ns("comparison_plot"), height = "340px"),
    tableOutput(ns("comparison_table")),
    p(
      "Left: the raw hit rate by race. Right: the ",
      "Threshold Test's corrected estimate of the actual suspicion bar. ",
      "They're on different scales, so compare direction, ",
      "not size; if a race's bar is lower under both methods, the ",
      "correction didn't explain the naive gap away."
    ),
    uiOutput(ns("comparison_interpretation"))
  )
}

threshold_module_server <- function(id, results_dir, reference_race = "white") {
  moduleServer(id, function(input, output, session) {
    threshold_data <- reactive({
      path <- file.path(results_dir, "threshold_test.rds")
      validate(need(file.exists(path), paste0("No cached result at ", path, " -- run `make results` first.")))
      readRDS(path)
    })

    comparison <- reactive({
      duboisR::compare_outcome_threshold_test(
        threshold_data()$suff_stats, threshold_data()$fit,
        reference_race = reference_race
      )
    })

    output$search_rate_plot <- renderPlot({
      duboisR::plot_county_search_disparity(threshold_data()$county_search_disparity)
    })

    output$search_rate_interpretation <- renderUI({
      p(strong("What this data shows: "), duboisR::interpret_search_rate_disparity(
        threshold_data()$county_search_disparity, reference_race = reference_race
      ))
    })

    output$threshold_plot <- renderPlot(plot(threshold_data()$fit))

    output$threshold_interpretation <- renderUI({
      p(strong("What this data shows: "), duboisR::interpret_threshold_fit(threshold_data()$fit, reference_race = reference_race))
    })

    output$comparison_plot <- renderPlot({
      duboisR::plot_outcome_threshold_comparison(comparison(), reference_race = reference_race)
    })

    output$comparison_table <- renderTable({
      comparison() |>
        dplyr::select(
          Race = race, `Hit Rate` = hit_rate, `Hit Rate Gap` = hit_rate_gap,
          `Inferred Threshold` = mean_threshold_weighted, `Threshold Gap` = threshold_gap,
          `Agrees in Direction` = agrees_in_direction
        )
    })

    output$comparison_interpretation <- renderUI({
      p(
        strong("What this data shows: "),
        duboisR::interpret_outcome_threshold_comparison(comparison(), reference_race = reference_race)
      )
    })
  })
}
