# Seeds a first-pass, realistic datasheet.json for the demo, grounded in
# the actual pipeline/data (not placeholder text) -- the check_proxies()
# and check_tendentious() figures below were computed against the real
# dataset, not invented. Uses duboisR::seed_datasheet_answers(), which
# merges into any existing datasheet.json rather than replacing it: an
# existing non-empty answer at each question is left untouched unless
# overwrite_existing = TRUE is passed. Re-running this script is therefore
# safe even after a human has started editing the file by hand or via
# duboisR::build_datasheet_wizard() -- their edits win.
#
# Run from the repo root: Rscript duboisR/inst/scripts/seed_demo_datasheet.R
# Pass --overwrite to force these answers over existing ones instead.

source("duboisR/inst/scripts/_load_duboisR.R")
load_duboisR_or_die("duboisR")

OUTPUT_PATH <- "data/processed/datasheet.json"
OVERWRITE_EXISTING <- "--overwrite" %in% commandArgs(trailingOnly = TRUE)

answers <- list(
  motivation = list(
    purpose = paste(
      "To power the \"Algorithms of Discretion\" audit dashboard and its",
      "accompanying white paper: examining how socioeconomic and",
      "spatial/environmental covariates modify (or fail to modify) apparent",
      "racial disparities in Texas traffic stops. A Du Boisian/QuantCrit",
      "computational audit of administrative policing data -- not a",
      "predictive or risk-scoring tool."
    ),
    funder = paste(
      "No external funder. Independent research project by Patrick Eugene",
      "Porche Jr., built entirely on the public Stanford Open Policing",
      "Project data release and the freely available U.S. Census Bureau",
      "ACS API."
    )
  ),
  composition = list(
    instances = paste(
      "Each row is one traffic stop conducted by the Texas Department of",
      "Public Safety (State Patrol), restricted to 2015-2017 (3 of the",
      "2006-2017 years in Stanford's release -- a performance decision to",
      "keep glm() refits interactive at ~5.6M rows, not a methodological",
      "one) and to drivers recorded as white, black, or hispanic (~5.6M of",
      "~27.4M raw rows). Other race categories were dropped rather than",
      "binned into \"other\", for insufficient sample size to support",
      "stable disparity estimates."
    ),
    subpopulations = paste(
      "subject_race (white/black/hispanic) and subject_sex (male/female).",
      "See the live composition table above for exact counts and",
      "missingness by race."
    ),
    sensitive_data = paste(
      "Yes: race, sex, and -- via county_fips -- a strong geographic",
      "correlate of race. A duboisR::check_proxies() run",
      "(subject_race ~ county_fips + poverty_rate + median_income + hour,",
      "random forest, 300k-row sample) predicts race at 67.8% accuracy",
      "against a 47.1% no-information baseline -- a 20.8-point lift, led by",
      "poverty_rate and median_income. County-level socioeconomic covariates",
      "meant to \"control for\" structural factors are themselves",
      "substantially race-correlated here (consistent with historical",
      "redlining/residential segregation), so \"controlling for poverty\"",
      "does not cleanly separate race from class in this data."
    ),
    missing_info = paste(
      "contraband_found is structurally NA for ~98-99% of rows (see the",
      "live composition above): it is only defined when",
      "search_conducted == TRUE, and searches are rare (~1.6% base rate).",
      "search_conducted itself is NA for roughly a third of rows --",
      "Stanford's own reporting gap, not something this pipeline introduces.",
      "Neither subject_age nor an arrest outcome exists in the Texas State",
      "Patrol file at all -- not missing data, just never collected or",
      "reported by this agency."
    )
  ),
  collection_process = list(
    acquisition = paste(
      "Administrative records generated by DPS troopers at the time of each",
      "stop, standardized and released by the Stanford Open Policing",
      "Project (stacks.stanford.edu, druid:yg821jf8611, \"TX statewide\"",
      "file, released 2020-04-01). County-level median household income",
      "and poverty rate are pulled separately via the U.S. Census Bureau's",
      "ACS 5-Year API (2022 vintage) and joined on normalized county name",
      "(the raw stop file carries no county FIPS)."
    ),
    collectors_timeframe = paste(
      "Stops: Texas DPS troopers, statewide, over the full 2006-2017 window",
      "in Stanford's release; this pipeline uses only 2015-2017 of that.",
      "Standardization into Stanford's common schema: the Stanford Open",
      "Policing Project team. Census join: pulled directly from the Census",
      "API by this project's own pipeline (python/01_fetch_census.py), not",
      "by Stanford."
    ),
    ethical_review = paste(
      "None conducted by this project -- these are pre-existing public",
      "administrative records and a public government statistical API,",
      "not newly collected human-subjects data. No IRB review was sought",
      "or is understood to be required for secondary analysis of an",
      "already-public, de-identified administrative dataset."
    )
  ),
  preprocessing = list(
    was_preprocessed = paste(
      "Yes -- see python/01-03 and the Makefile DAG. Filtered to 2015-2017",
      "and to white/black/hispanic subject_race; hour derived from a",
      "combined date+time parse; county_join_key derived by normalizing",
      "county_name text to join against Census data."
    ),
    raw_data_saved = paste(
      "Yes -- the original Stanford .zip and the Census API's raw response",
      "are both kept in data/raw/ (gitignored, regenerable via `make all`),",
      "separate from the merged, filtered",
      "data/processed/audit_ready_stops.csv this dashboard actually reads."
    ),
    software_available = "Yes -- the full pipeline (python/, duboisR/, r_dashboard/, Makefile) is in this repository.",
    identity_proxies = paste(
      "Yes, substantially -- see composition.sensitive_data above",
      "(duboisR::check_proxies(): 67.8% vs. 47.1% baseline, +20.8 points,",
      "led by poverty_rate and median_income)."
    )
  ),
  uses = list(
    prior_uses = paste(
      "This project only: the \"Algorithms of Discretion\" audit dashboard",
      "and its accompanying white paper. The underlying Stanford Open",
      "Policing data has been used broadly across academic policing",
      "research, including the original Veil of Darkness and outcome-test",
      "literature this project builds on."
    ),
    composition_impact = paste(
      "The 2015-2017 / white-black-hispanic restriction means findings",
      "here should not be read as representative of the full 2006-2017",
      "Texas record, of Texas racial groups outside these three",
      "categories, or of any state other than Texas. See also the",
      "identity-proxy finding above: any model that \"controls for\"",
      "county-level poverty or income is not cleanly isolating race from",
      "class in this data."
    ),
    inappropriate_uses = paste(
      "Not for individualized decisions about any specific driver, officer,",
      "or department -- this is an aggregate statistical audit of",
      "disparity patterns, not a risk-scoring or officer-evaluation tool.",
      "search_conducted and contraband_found are both classified as",
      "administrative outcomes (duboisR::check_tendentious()), not",
      "objective ground truth: they reflect officer discretion (who gets",
      "searched) compounded with what a search happens to find, not an",
      "unbiased measurement of who was carrying contraband. Models trained",
      "on them risk reproducing that discretion rather than measuring an",
      "underlying fact -- see the Regression / Veil of Darkness /",
      "Threshold Test tabs for how this project tries to make that",
      "discretion visible rather than launder it into a single \"risk\"",
      "number."
    )
  ),
  distribution = list(
    third_parties = paste(
      "This project's derived dataset (data/processed/audit_ready_stops.csv)",
      "is not distributed; it's regenerated locally from the two public",
      "sources via `make all`. The underlying Stanford Open Policing data",
      "and Census ACS estimates are both already public."
    ),
    distribution_mechanism = paste(
      "Not distributed as a standalone dataset. The dashboard",
      "(r_dashboard/) is intended to be hosted for read-only demo access",
      "rather than distributed as a downloadable app -- see README."
    ),
    licensing = paste(
      "Stanford Open Policing Project data: released for research use",
      "(see openpolicing.stanford.edu for current terms). U.S. Census",
      "Bureau ACS estimates: U.S. government public-domain data. This",
      "project's own code is MIT-licensed (root LICENSE; duboisR/ also",
      "carries its own copy via DESCRIPTION's License field)."
    )
  ),
  maintenance = list(
    maintainer = "Patrick Eugene Porche Jr., as part of the \"Algorithms of Discretion\" white paper project.",
    contact = "porchewellness@gmail.com (see DESCRIPTION).",
    updates = paste(
      "No update schedule -- this is a frozen, point-in-time dataset",
      "(2015-2017) for a specific research project, not a live feed. See",
      "the README's \"Pointing the pipeline at a different state\" section",
      "for how to rebuild against a different state or a refreshed",
      "Stanford release."
    ),
    erratum = "No formal process yet -- open an issue/PR against this repository."
  )
)

seed_datasheet_answers(answers, path = OUTPUT_PATH, overwrite_existing = OVERWRITE_EXISTING)
cat("Wrote", OUTPUT_PATH, if (OVERWRITE_EXISTING) "(overwrote existing answers)\n" else "(existing answers, if any, were preserved)\n")
